FROM php:7.1.2-apache
RUN docker-php-ext-install mysqli
RUN apt-get update && \
    apt-get install -y \
        sendmail libpng-dev zlib1g-dev libjpeg-dev libfreetype6-dev
RUN docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install gd
RUN docker-php-ext-install zip
RUN a2enmod rewrite